-- ============================================================================
-- ERP product canonicalisation + ERP-derived blow-time benchmarks.
--
-- The ERP `Descr` field is free text, so one product appears under dozens of
-- spellings (Econo Bark / ECONO BARK / ECONO--Bark / Econo-bark / ...). Left
-- unmerged they splinter into ~150 near-empty buckets and per-product hour
-- benchmarks are useless. This adds orders.product -- the rate-card name each
-- description maps to -- and backfills it.
--
-- Run once, then re-run sql/03_seed_reference.sql to load the new benchmarks.
-- Safe to re-run.
--
-- NB: the mapping is inlined as a VALUES list inside a single UPDATE rather
-- than staged in a temp table. The SQL editor runs each statement in its own
-- transaction, so a `create temporary table ... on commit drop` is gone before
-- the next statement can use it.
-- ============================================================================

alter table orders          add column if not exists product text;
alter table blow_benchmarks add column if not exists source  text;

create index if not exists idx_orders_canon_product on orders(product, total_yards);

update orders o
   set product = m.canon
  from (values
    ('1/4  -10 quarry rock', 'Quarter Ten from RiverBend'),
    ('1/4 " #10 rock-Retail Drop Ship', 'Quarter Ten from RiverBend'),
    ('1/4 " 10 rock -Retail Drop Ship', 'Quarter Ten from RiverBend'),
    ('1/4-10 Quarry', 'Quarter Ten from RiverBend'),
    ('1/4-10 rock-Retail Drop Ship', 'Quarter Ten from RiverBend'),
    ('3/4 Open', '3/4" open quarry from Coburg Quarry'),
    ('3/4 Open crushed river RK', '3/4" open quarry from Coburg Quarry'),
    ('3/4 Open-Retail Drop Ship', '3/4" open quarry from Coburg Quarry'),
    ('3/4" PCC rock from RiverBend', '3/4" round rock from RiverBend'),
    ('3/4" Round-Retail Drop Ship', '3/4" round rock from RiverBend'),
    ('3/4" open', '3/4" open quarry from Coburg Quarry'),
    ('3/4" river crushed open-Retail Drop Ship', '3/4" open quarry from Coburg Quarry'),
    ('3/8 Round Pea Gravel-Retail Dr', '3/8" round rock from RiverBend'),
    ('BLACK---UltraKote', 'UltraKote'),
    ('BLACK--UltraKote', 'UltraKote'),
    ('BLACK-UltraKote', 'UltraKote'),
    ('BLack--UltraKote', 'UltraKote'),
    ('BeautiBark', 'BeautiBark'),
    ('Beautibark', 'BeautiBark'),
    ('Black -UltraKote', 'UltraKote'),
    ('Black UltraKote', 'UltraKote'),
    ('Black Ultrakote', 'UltraKote'),
    ('Black---UltraKote', 'UltraKote'),
    ('Black--UltraKote', 'UltraKote'),
    ('Black-UltraKote', 'UltraKote'),
    ('DARH--- Hemlock Bark', 'Hemlock'),
    ('DARK  Beautibark', 'BeautiBark'),
    ('DARK  Hemlock', 'Hemlock'),
    ('DARK BeautiBark', 'BeautiBark'),
    ('DARK Beautibark', 'BeautiBark'),
    ('DARK HEMLOCK', 'Hemlock'),
    ('DARK Hemlock', 'Hemlock'),
    ('DARK Hemlock Bark', 'Hemlock'),
    ('DARK-- BeautiBark', 'BeautiBark'),
    ('DARK-- Hemlock Bark', 'Hemlock'),
    ('DARK--- Hemlock Bark', 'Hemlock'),
    ('DARK---BeautiBark', 'BeautiBark'),
    ('DARK---Hemlock Bark', 'Hemlock'),
    ('DARK--BeautiBark', 'BeautiBark'),
    ('DARK--Hemlock Bark', 'Hemlock'),
    ('DARK-Extra Fine Bark', 'Extra Fine Bark'),
    ('Dark BeautiBark', 'BeautiBark'),
    ('Dark Beautibark', 'BeautiBark'),
    ('Dark Extra fine bark', 'Extra Fine Bark'),
    ('Dark Hemlock', 'Hemlock'),
    ('Dark-- Hemlock Bark', 'Hemlock'),
    ('Dark--BeautiBark', 'BeautiBark'),
    ('Dark--Beautibark', 'BeautiBark'),
    ('Dark--Hemlock Bark', 'Hemlock'),
    ('Darker Beautibark', 'BeautiBark'),
    ('Darkest--BeautiBark', 'BeautiBark'),
    ('DecoBark Nuggets', 'DecoBark Nuggets'),
    ('ECONO  -BARK', 'Econo-Bark'),
    ('ECONO - BARK', 'Econo-Bark'),
    ('ECONO BARK', 'Econo-Bark'),
    ('ECONO Bark', 'Econo-Bark'),
    ('ECONO- Bark', 'Econo-Bark'),
    ('ECONO-- Bark', 'Econo-Bark'),
    ('ECONO--- Bark', 'Econo-Bark'),
    ('ECONO--BARK', 'Econo-Bark'),
    ('ECONO--Bark', 'Econo-Bark'),
    ('ECONO-BARK', 'Econo-Bark'),
    ('Econo', 'Econo-Bark'),
    ('Econo -Wholesale Bark', 'Econo-Bark'),
    ('Econo Bark', 'Econo-Bark'),
    ('Econo Wholesale Bark', 'Econo-Bark'),
    ('Econo bark', 'Econo-Bark'),
    ('Econo--BARK', 'Econo-Bark'),
    ('Econo--Bark', 'Econo-Bark'),
    ('Econo-bark', 'Econo-Bark'),
    ('EconoBark', 'Econo-Bark'),
    ('Econobark', 'Econo-Bark'),
    ('Extra Fine Bark', 'Extra Fine Bark'),
    ('Extra Fine Bark-Retail Drop Sh', 'Extra Fine Bark'),
    ('FRESH  BeautiBark', 'BeautiBark'),
    ('FRESH -- Beautibark', 'BeautiBark'),
    ('FRESH Beautibark', 'BeautiBark'),
    ('FRESH HEMLOCK', 'Hemlock'),
    ('FRESH---BeautiBark', 'BeautiBark'),
    ('FRESH--BeautiBark', 'BeautiBark'),
    ('Fiberex', 'Fiberex'),
    ('Food Waste-- Compost', 'Garden Compost'),
    ('Fresh Beautibark', 'BeautiBark'),
    ('Fresh Fir Sawdust', 'Fresh Sawdust'),
    ('Fresh Hemlock', 'Hemlock'),
    ('Fresh Sawdust', 'Fresh Sawdust'),
    ('Fresh Sawdust-Retail Drop Ship', 'Fresh Sawdust'),
    ('Fresh--Beautibark', 'BeautiBark'),
    ('Fresh-Hemlock Bark', 'Hemlock'),
    ('G.V. Organic Garden Compost', 'Garden Compost'),
    ('GREENWASTE-- Compost', 'Garden Compost'),
    ('GVO Garden Compost', 'GVO Compost'),
    ('GVO all nat and organic with worm castings Potting soil', 'GVO Compost'),
    ('GVO with worm', 'GVO Compost'),
    ('GVO-- Garden Compost', 'GVO Compost'),
    ('GW Compost', 'Garden Compost'),
    ('Garden Mulch', 'Garden Mulch'),
    ('Garden Valley Natural and Organic Soil with Worm Castings', 'GVO Compost'),
    ('Garden Valley Organic Compost', 'GVO Compost'),
    ('Green Waste Compost', 'Garden Compost'),
    ('Green Waste- Compost', 'Garden Compost'),
    ('Green waste-- Compost', 'Garden Compost'),
    ('Greenwaste Compost', 'Garden Compost'),
    ('Greenwaste Garden Compost', 'Garden Compost'),
    ('Greenwaste- Compost', 'Garden Compost'),
    ('Greenwaste- Garden Compost', 'Garden Compost'),
    ('Greenwaste-- Compost', 'Garden Compost'),
    ('Greenwaste--Compost', 'Garden Compost'),
    ('Greenwaste--Garden Compost', 'Garden Compost'),
    ('Hemlock', 'Hemlock'),
    ('Love Food Not Waste Compost', 'Garden Compost'),
    ('Love Food not waste Compost', 'Garden Compost'),
    ('Love Food, Not Waste Compost', 'Garden Compost'),
    ('Love food not waste comp', 'Garden Compost'),
    ('Microblend', 'Microblend'),
    ('OPUS I-- Planting Mixes', 'Opus #1'),
    ('Opus #1', 'Opus #1'),
    ('Opus 1', 'Opus #1'),
    ('Opus Bio-Tope', 'Opus #1'),
    ('Premium Hemlock Bark', 'Hemlock'),
    ('Premium Hemlock-Retail Drop Sh', 'Hemlock'),
    ('Quarter Ten Rock', 'Quarter Ten from RiverBend'),
    ('Quarter Ten Rock from RiverBend', 'Quarter Ten from RiverBend'),
    ('RED---UltraKote', 'UltraKote'),
    ('RED---Ultrakote', 'UltraKote'),
    ('RED--UltraKote', 'UltraKote'),
    ('RED--Ultrakote', 'UltraKote'),
    ('Red UltraKote', 'UltraKote'),
    ('Red Ultrakote', 'UltraKote'),
    ('Red--UltraKote', 'UltraKote'),
    ('Rexius Flower-n-Garden', 'Flower-n-Garden'),
    ('Rexius Garden Compost', 'Garden Compost'),
    ('Rexius Patio Potting Soil', 'Patio Potting Soil'),
    ('Rexius Premium Turf Start', 'Turf Start'),
    ('Rexius Primary Planting Soil', 'Primary Planting Soil'),
    ('Rexius Steer Plus', 'Steer Plus'),
    ('Rexius Tree-n-Shrub', 'Tree-n-Shrub'),
    ('UltraKote', 'UltraKote'),
    ('all nat & org w worm cast', 'GVO Compost'),
    ('dark Beautibark', 'BeautiBark'),
    ('darker Beautibark', 'BeautiBark'),
    ('food waste compost', 'Garden Compost'),
    ('garden compost', 'Garden Compost'),
    ('greenwaste Compost', 'Garden Compost'),
    ('greenwaste Garden Compost', 'Garden Compost'),
    ('greenwaste-- Compost', 'Garden Compost'),
    ('gvo all org w worm castings Soil', 'GVO Compost'),
    ('love food not waste Compost', 'Garden Compost'),
    ('love food not wasteCompost', 'Garden Compost'),
    ('opus Bio-tope', 'Opus #1'),
    ('recycled Green Waste Compost', 'Garden Compost'),
    ('recycled green waste Compost', 'Garden Compost'),
    ('recycled green wasteCompost', 'Garden Compost'),
    ('recycled gw  Garden Compost', 'Garden Compost')
  ) as m(raw, canon)
 where btrim(o.primary_product) = m.raw
   and o.product is distinct from m.canon;

-- Anything still unmapped is genuinely not a blow-in product (Terra Seeding,
-- EcoBlanket, custom mixes, one-off job names typed into the product field).
-- select primary_product, count(*) from orders where product is null
--   and primary_product is not null group by 1 order by 2 desc;
